# Quick boot options
sudo: false
cache: yarn

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - 8
  - 9
  - 10
script:
  - yarn test

# Npm publish options
before_deploy:
  - yarn build
  
deploy:
  skip_cleanup: true # keep the devDependencies
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: fu3fcewGCtjFysnPlh9SbmVoLrTugy1bj9qBlggzUXyRWCUdbgCTTMJmvdrN1cBgBbVgo5/DU3PceCpqaw3pvUygDaq/iM/DIODFOgH/omcjbBGxv1O5c78z+kIW6iJoYRjWLImKIXUFaKrnHB2nd7MMZlYPTY1w3XKrqcZRal4wSSPK1qRZ1QrEQZZ3WcBv1CPiHWO/tu/nNeuM+XwHD7dJcF6M5vcUQNQvvANHkq9u895yYFRNnjDuaks/QUy2GkfVzmrLXVOoS6qCadTPD255SlF5MKftKSgl1mvXq0etICym940vrASBrz8mRn4rO+nHwVJTm7Jxkkhcjz30vtOjznYbz7Z/cucyvPeCxdOFYNZPh3VTUGXv0Djm2VzsoyM8hq6zpd/9vvwgfcS8s89JUbTXv0VIS0g+7rpuitalfWUVTQ1DaWt1o0OtAnR5se7E/3fH/pAS+PlFUL8MJI1PKEgFXv84IfX2jtImDzwotOMBkC1ROTFrvdgGHp4Q7LXB6bfwmCxiA9SvhnIkfaRNqg3hmR6WpFPFPb9X9oHFWlCqvxCqLSKsgy/m33W4F5nOVI47nx2h147zP/2WtAH6lN+CGlMjwwVEtx8E6IgfA2CNw3uYaKIQbVX6g+oD4IHo36XBcNausp9mI/ocD0MkVpCudskXz0DTVoSJMsk=
  on:
    node: 8
