# Quick boot options
sudo: false
cache: yarn

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - 8
  - 9
  - 10
script:
  - yarn test

# Npm publish options
before_deploy:
  - yarn build
  
deploy:
  skip_cleanup: true # keep the devDependencies
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: BoAS7FneI3JQsgXm+u2P5HC9hcc2o8uaGmv4pqSuYtBcPhYNR+coqBKHxyAUT0OyoqNAl1u0PiKmbvxSirEpV0LEvQqL/RtFyRkmO9B6HlikzXVi6glBULJoMWNXMwEXqHLW4VJd8+9iCj3ad4daJPiRSc00WT8vqnBCXwFKe/cPc0Ct0u4gufemcyfG7CoBc1vN/8FN2B36A4HxqXmZhqPl6Wqyplx8sG3pSmuNlhG51BIZIWYtlbWNKXC+bzWj3iphKrJeLVxf8KCZbRUTuYkDRl+DwSRVBtvhO6xgnhCzZliG2u+eN88P/Yq9Pqy59U3FgRo9zOYqJhxqOXo5SypJA6idAF4my6/K5H7yOGVZ4tblEByf2pJvlkJBOVwAWI+u8OvxI1JZeSKTCdR+rrGFEg6cYGtqvN2WqFhSf7iKOGpy8WsfwbwvG/h+kJFxK3C6URLmKh+6EdtLCISsF8/9xdlKeCm1gWpdWifIfLYVUlzIIuev8wOgW5ehzLmZYUgxNReOKBtdm0KXuLhVjch6Op550u5CbxcFGHJerUYLNnD0GDVDMOjpw6rMDU1Z9b0ZJg/IPAE86yopfDLFqHupR/bZPKVzm5W8qWmTIUF8v/lyHEJri/Tv3RFbi8SxjYaSYntPL+jr4BRr9KZgNe1pV1bFQkcYBc5dKd4bBHU=
  on:
    node: 8
