# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - 8
  - 9
  - 10
before_script:
  - npx flow-typed install -s -o --ignoreDeps peer
script:
  - yarn test
  - yarn lint
  - yarn flow

# Npm publish options
before_deploy:
  - yarn build
deploy:
  skip_cleanup: true # keep the devDependencies
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: WAbIpvXXNlEcRdHvWQ5KrJ/VRbo75dhXWvVFvkIb3HKdC3kwn20rTfE2DnTkjmnjhW5aeWNd53E+o5EzlG45Ymq4qg1GM1/09V9f0zHMEp8FzvOLL2GFn1dc5i8k5wlfLMIWAVAXkLhocAs0JtqR8tkLpiT1r6lS9zFomNCBQ5ldM41qjKXzqV5crzrviFDJ6C0zTJdY62M1OJ8CU4ko0N79HGP0Ty0CrfZ6Rxz0iZqWORlRICaCN9GH0urk19FlnNux17ozDYrz14bhiaDsy/RhZh3o9Qv1OPAfZ32tNDCHe9mRzu7FCWRkHHrlBqRU1WNmd2wrMOKE7yicZksU+d8skw5JR4V9WaLOuCaB2KTI6P1WxONvfRwDO4Cj49zsZtb84k76nGA6XfrrLsknQ7wq/Beyuvw0b5PzMYZy4FJUYQ4ROog4+5AH09vN5AwJJ25MM89qDzRFhjA1qGcECIiyQyhVhWFJUVJZauPm+EBvEYtLdk4j4XMnuA/4/vHkflZASkw/zsBD0mWUty9iZt4GYFQ849z/Ww2B+d9kjZ8BA6WqI/m1+zCUONUGVIG2rWkti/9xfr2zWwkYaxqm9sK3pY0ftX9stN19KOf7Y5RvgVxrpn88QmEdpNBJcQtDVW+e9LqT81JIHHV081oU7d2YyC0fD1pEcAK/BGUZPMA=
  on:
    node: 8
